apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rollingupdate
spec:
  selector:
    matchLabels:
      app: app-rollingupdate
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-rollingupdate
    spec:
      containers:
        - name: hello-app
          image: gcr.io/google-samples/hello-app:2.0
          resources:
            limits:
              cpu: '0.5'
              memory: '64Mi'
            requests:
              cpu: '0.25'
              memory: '32Mi'
          ports:
            - containerPort: 8080
